# Generated by Django 5.1.15 on 2026-03-15 11:14

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_vector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('confidence', models.FloatField()),
                ('pixel_bbox', models.JSONField(default=dict)),
                ('normalized_bbox', models.JSONField(default=dict)),
                ('geo_bbox', models.JSONField(blank=True, default=dict)),
                ('tile_bbox', models.JSONField(blank=True, default=dict)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('relabeled', 'Relabeled')], default='pending', max_length=32)),
                ('verification_state', models.CharField(choices=[('not_run', 'Not run'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='not_run', max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('crop', models.ImageField(blank=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('exif_metadata', models.JSONField(blank=True, default=dict)),
                ('georeference', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='created', max_length=32)),
                ('classes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='vision.detection')),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vision.imageasset'),
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('current_stage', models.CharField(default='queued', max_length=64)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='vision.imageasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='vision.project')),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vision.inferencerun'),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vision.project'),
        ),
    ]
