# Generated by Django 5.1.15 on 2026-03-15 15:36

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingrecord",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=512),
        ),
    ]
